import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'fs'
import path from 'path'

// Read the local API token generated by the backend at startup.
// The token file lives at .runtime/api-token (gitignored).
// Falls back to LOCAL_API_TOKEN env var for CI / headless environments.
function readLocalToken(): string {
  const tokenFile = path.resolve(__dirname, '../../.runtime/api-token')
  try {
    return fs.readFileSync(tokenFile, 'utf-8').trim()
  } catch {
    return process.env.LOCAL_API_TOKEN ?? ''
  }
}

// https://vitejs.dev/config/
export default defineConfig({
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore — vite version mismatch between workspace (v7) and frontend (v6)
  plugins: [react()],
  server: {
    proxy: {
      '/api': {
        target: 'http://127.0.0.1:3001',
        changeOrigin: true,
        configure: (proxy) => {
          // Attach auth token on every proxied request so the frontend
          // never needs to manage the token itself.
          proxy.on('proxyReq', (proxyReq) => {
            const token = readLocalToken()
            if (token) proxyReq.setHeader('Authorization', `Bearer ${token}`)
          })
        },
      },
    },
  },
})
